services:
  app_dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '${PORT}:5000'
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: db_dev
      POSTGRES_PORT: ${POSTGRES_PORT}
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      ACCESS_TOKEN_EXPIRATION: ${ACCESS_TOKEN_EXPIRATION}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      REFRESH_TOKEN_EXPIRATION: ${REFRESH_TOKEN_EXPIRATION}
      CHOKIDAR_USEPOLLING: true
    depends_on:
      - db_dev
    # command: sh -c "npm install && npm run typeorm:migration:run && npm run typeorm:seed && npm run start:dev"
    command: npm run start:dev
    volumes:
      - .:/app
    profiles: ['dev']

  db_dev:
    image: postgres:16
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    profiles: ['dev']
  
  app_prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT}:5000'
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: db_prod
      POSTGRES_PORT: ${POSTGRES_PORT}
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      ACCESS_TOKEN_EXPIRATION: ${ACCESS_TOKEN_EXPIRATION}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      REFRESH_TOKEN_EXPIRATION: ${REFRESH_TOKEN_EXPIRATION}
    depends_on:
      - db_prod
    command: sh -c "npm run typeorm:migration:run && npm run typeorm:seed && npm run start:prod"
    volumes:
      - .:/app
    profiles: ['prod']

  db_prod:
    image: postgres:16
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
    profiles: ['prod']

volumes:
  pgdata_dev:
  pgdata_prod:
